apiVersion: v1
kind: Namespace
metadata:
  name: epsagon-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-agent
  namespace: epsagon-monitoring
spec:
  selector:
    matchLabels:
      app: epsagon-cluster-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: epsagon-cluster-agent
    spec:
      serviceAccountName: cluster-agent
      containers:
      - name: cluster-agent
        image: epsagon/cluster_agent:v1.0.0
        imagePullPolicy: Always
        env:
        - name: EPSAGON_TOKEN
          value: ""
        - name: EPSAGON_CLUSTER_NAME
          value: ""
        - name: EPSAGON_DEBUG
          value: "false"
        - name: EPSAGON_COLLECTOR_URL
          value: "https://collector.epsagon.com/resources/v1"
