apiVersion: v1
kind: Namespace
metadata:
  name: epsagon-monitoring
  labels:
    name: epsagon-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-agent
  namespace: epsagon-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-agent
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - namespaces
  - configmaps
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-agent-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-agent
subjects:
- kind: ServiceAccount
  name: cluster-agent
  namespace: epsagon-monitoring
