name: Create Cluster

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies # no if here since we still need to install from pip cache
        timeout-minutes: 5
        working-directory: ./pkg/cluster_agent
        run: |
          pip install pip==21.0.1
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: test
        timeout-minutes: 1
        working-directory: ./pkg/cluster_agent
        run: pytest ./tests/ut


  agent-sanity-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          cluster_name: test-cluster

      - uses: actions/checkout@v2

      - name: test-docker
        run: which docker
        working-directory: ./pkg/cluster_agent

      - name: build-image
        run: docker build . -t epsagon/cluster-agent:test -f ./build/Dockerfile
        working-directory: ./pkg/cluster_agent

      - name: load-image-to-kind
        run: kind load docker-image epsagon/cluster-agent:test --name test-cluster

      - name: deploy-epsagon-role
        run: kubectl apply -f ./epsagon_role.yaml
        working-directory: ./pkg/cluster_agent

      - name: deploy-agent-deployment
        run: kubectl apply -f ./tests/test_agent_deployment.yaml
        working-directory: ./pkg/cluster_agent

      - name: test-agent-container-running
        run: sleep 10 && kubectl -n epsagon-monitoring get pods | grep cluster-agent | grep Running
